### ISSUE TITLE
travel_planの編集での動作

### ISSUE THREAD

**Issue by HIROHIRO1224** [joetsu-san/tabinoshiori-frontend#142]
旅のしおりのページで観光地の順番を入れ替える事が出来ない
更にタイトルや説明、スポットの追加をした際にリロードをかけないと変更が反映されない。
これは2023/7/23 1:30現在デプロイされているものでスマホでもPCでも行うことが出来ない。

**Comment by nnsyobo** [comment]
今から修正を始めます

**Comment by nnsyobo** [comment]
> 旅のしおりのページで観光地の順番を入れ替える事が出来ない
これについては #128 が先発だったため、このIssueでは無視します
